#!/bin/sh
lock() {
    setxkbmap -layout us
    sleep 1s # waiting for change to take effect
    setxkbmap -layout us,us,ru -variant ,colemak, -option 'grp:rshift_toggle'
    betterlockscreen --off 300 -l blur -b 0.7
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
